---
title: "Export_html_tables"
author: "Pauline"
date: '2022-05-06'
output: html_document
---
This file exports the tables formatted as html. This is an easy and visual way to present the data.
```{r setup, include = F}
library(tidyverse)
library(reactablefmtr)

#colours
library(IUCNpalette)
library(readxl)
library(xlsx)
IUCN_palette <- iucn_palette()
IUCN_palette[1] <- "lightgray"
IUCN_palette[8] <- "black"
IUCN_palette[9] <- "lightskyblue"
names_IUCN <- names(iucn_palettes)[1:8]

#select species (take 'commentaire' to have outdated names as well)
elasmo_FR <- read.csv("data\\elasmo_uicn_france.csv") %>% mutate(Genre = word(.$Species, 1))
species_names <- c(elasmo_FR$Species, elasmo_FR$Species) %>% unique() %>% na.exclude()
species_genre <- paste0(unique(elasmo_FR$Genre), " spp") %>% na.exclude()
species_all <- c(species_names, species_genre)
```

# Load data
```{r data}
#load elasmo table
Elasmobranchs_IUCN_historical_status <- read.csv("data\\Elasmobranchs_IUCN_historical_status.csv", encoding = "UTF-8", check.names = F) %>% select(-"Before_last_evaluation", -"Before_last_status")

#Conventions
Appendices <- read.csv("data\\Species_cited_in_appendices.csv", check.names = F, sep = ";") %>% 
  na_if("NA") %>% na_if(NA) %>% na_if("")

#OSPAR Status
##POSH
Status_OSPAR <- read.csv("data\\Status_OSPAR.csv", encoding = "UTF-8", check.names = F, sep = ";") #to have symbols

##FC1
FC1_OSPAR <- readxl::read_xlsx("data\\FC1_integrated_outcomes.xlsx")

#ICES
ICES_stock_cat <- read.csv("data\\ICES_stock_categories.csv", encoding = "UTF-8", check.names = F) %>% select(-1) %>%
  rename(Stock = stock)#drop id col
ICES_advice <- read.csv("data\\ICES_advice_history.csv", encoding = "UTF-8", check.names = F) %>% select(-1) #drop 1st id col
```

# Elasmo historical table
```{r display_iucn}
#need to convert all to character
Elasmobranchs_IUCN_historical_status <- Elasmobranchs_IUCN_historical_status %>% mutate(across(everything(), as.character)) %>%
  relocate(Last_status, .after = Region)

Elasmobranchs_IUCN_historical_status[is.na(Elasmobranchs_IUCN_historical_status)] <- " " #replace NAs by blank for better visualisation
colnames(Elasmobranchs_IUCN_historical_status)

#translate
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "Baltic Sea"] <- "Baltique"
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "Mediterranean Sea"] <- "Méditerranée"
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "Croatia"] <- "Croatie"
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "Italy"] <- "Italie"
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "Ireland"] <- "Irlande"
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "World"] <- "Monde"
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "Sweden"] <- "Suède"
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "Norway"] <- "Norvège"
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "Albania"] <- "Albanie"
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "Germany"] <- "Allemagne"
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "United Kingdom"] <- "Royaume-Uni"
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "NE Atlantic"] <- "Atlantique NE"
Elasmobranchs_IUCN_historical_status$Region[Elasmobranchs_IUCN_historical_status$Region == "World"] <- "Monde"
Elasmobranchs_IUCN_historical_status$Level[Elasmobranchs_IUCN_historical_status$Level == "Regional"] <- "Régional"

#Translate the column names to french
Elasmobranchs_IUCN_historical_status <- Elasmobranchs_IUCN_historical_status %>% 
  rename(Espèce = 1,
         `Nom commun` = Nom.commun,
         Niveau = Level,
         Région = Region,
         `Dernier statut` = Last_status,
         `Evolution du statut` = Status_evolution,
         `Années écoulées` = Years_apart,
         `Dernière évaluation` = Last_evaluation)

#Appendices table to long format
Appendices[Appendices == "X"] <- " "

Appendices_long <- Appendices %>% select(-CITES_listing_year) %>%
  rename(Berne = BERN_appendix, Barcelone = Barcelona_appendix, Washington = CITES_appendix, Bonn = CMS_appendix,
         Espèce = "ï»¿Species") %>%
  mutate_all(as.character) %>%
  pivot_longer(cols = "Berne" : OSPAR, names_to = "conventions", values_to = "Détail", values_drop_na = T) %>%
  unite(conventions:"Détail", col = conventions, remove = TRUE, sep = " ", na.rm = T) %>%
  pivot_wider(values_from = "conventions", names_from = "conventions") %>% #group by wasn't working
  unite("Washington II" : "Washington I", col = Conventions, remove = T, sep = ", ", na.rm = T)

Elasmobranchs_IUCN_historical_status <- left_join(Elasmobranchs_IUCN_historical_status, Appendices_long) %>% 
  relocate("Conventions", .after = "Nom commun") %>% mutate(across(everything(), as.character))

write.xlsx(Elasmobranchs_IUCN_historical_status, "data\\Elasmo_final_table.xlsx", showNA = F, col.names = T)

#elasmo to bind
elasmo_binding <- Elasmobranchs_IUCN_historical_status %>% select(Espèce, "Nom commun", "Conventions") %>% unique()

#Add OSPAR status for french waters (II to IV)
POSH <- Status_OSPAR %>% filter(Region %in% c("II", "III", "IV")) %>%
  mutate(Region = paste0("OSPAR ", Region, "(POSH)"), "2021" = Last_status) %>% 
  rename("Dernier statut" = Last_status, "Dernière évaluation" = Year, "Espèce" = Species, "Région" = Region) %>%
  select(-Previous_status, -Common_name) %>%
  mutate(Niveau = "Régional") %>%
  mutate_all(as.character) %>%
  left_join(., elasmo_binding)
  

#FC1
FC1 <- FC1_OSPAR %>% filter(species %in% species_names) %>% filter(variable == "Long") %>% #keep only long term trend
  mutate(msfd.region = case_when(
    msfd.region == "BBIC" ~ "OSPAR IV (FC1)",
    msfd.region == "GNS" ~ "OSPAR II (FC1)",
    msfd.region == "CS" ~ "OSPAR III (FC1)"
  )) %>%
  mutate("2022" = bi.res) %>%
  rename("Espèce" = species, "Région" = msfd.region, "Dernier statut" = bi.res) %>% 
  select(Espèce, Région, "Dernier statut", "2022") %>%
  mutate(Niveau = "Régional", "Dernière évaluation" = "2022") %>%
  mutate_all(as.character) %>%
  left_join(., elasmo_binding)
  

Elasmo_with_OSPAR <- full_join(Elasmobranchs_IUCN_historical_status, FC1) %>% full_join(., POSH)

#add ices and iccat
ICCAT_GFCM <- read.csv("data\\Status_ICCAT_GFCM.csv", sep = ";") %>%
  mutate("Dernière évaluation" = Year, "Dernier statut" = Last_status) %>%
  pivot_wider(values_from = Last_status, names_from = Year) %>%
  mutate("Région" = case_when(
    Region == "NE Atlantic" ~ "CICTA : Atlantique NE",
    Region == "Ligurian and Tyrrhenian Seas" ~ "CGPM : Méditerranée (Ligurienne et Tyrrhenienne)" 
  ),
  Niveau = "Régional") %>%
  rename("Espèce" = Species) %>%
  select(-Region, -variable) %>%
  mutate_all(as.character) %>%
  full_join(., Appendices_long) %>% 
  relocate("Conventions", .after = "Espèce") %>% mutate(across(everything(), as.character)) %>% left_join(.,names_elasmo) %>% relocate(c("Nom commun", "Nom anglais"), .after = "Espèce")
  
#bind with elasmo
Elasmo_with_OSPAR <- full_join(Elasmo_with_OSPAR, ICCAT_GFCM) %>% dplyr::filter(!grepl("CIEM",Région))
Elasmo_with_OSPAR <- Elasmo_with_OSPAR %>% dplyr::filter(!grepl("CIEM",Région))

#add cIEM
ICES <- read_xlsx("data\\ICES_qualitative_stock_eval.xlsx") %>% rename("Espèce" = Species) %>% select(-"Eco Region") %>%
  mutate(Région = case_when(
    Region == "NE Atlantic" ~ "CIEM : Atlantique NE",
    Region == "GNS" ~ "CIEM : Mer du Nord",
    Region == "CS (North)" ~ "CIEM : Mers celtiques (Nord)",
    Region == "CS (South)" ~ "CIEM : Mers celtiques (Sud)",
    Region == "BBIC (North)" ~ "CIEM : Golfe de Gascogne (Nord)",
    Region == "BBIC (South)" ~ "CIEM : Golfe de Gascogne (Sud)",
    Region == "CS" ~ "CIEM : Mers celtiques"
  ),
  Niveau = "Régional",
  "Dernier statut" = ifelse(is.na(`2019`), `2018`, `2019`)) %>% select(-Region, -Stock) %>%
  mutate_all(as.character) %>%
  full_join(., Appendices_long) %>% 
  relocate("Conventions", .after = "Espèce") %>% mutate(across(everything(), as.character)) %>% left_join(.,names_elasmo) %>% relocate(c("Nom commun", "Nom anglais"), .after = "Espèce")


ICES[ICES == "inc"] <- "increasing"
ICES[ICES == "dec"] <- "decreasing"

#bind with elasmo
Elasmo_with_OSPAR <- full_join(Elasmo_with_OSPAR, ICES) %>% mutate_all(as.character)

#export
write.xlsx(Elasmo_with_OSPAR, "data\\Elasmo_final_table_with_OSPAR.xlsx", showNA = F, col.names = T)
```

## HTML final table
```{r}
#df with names
names_elasmo <- read_xlsx("data\\Elasmobranches_présents_FR.xlsx") %>% select(3:5)

#final df
Elasmo_with_OSPAR <- read_xlsx("data\\Elasmo_final_table_with_OSPAR.xlsx") %>% drop_na("Dernier statut") %>% select(-1) %>% select(-"Nom commun") %>% left_join(.,names_elasmo) %>% relocate(c("Nom commun", "Nom anglais"), .after = "Espèce") %>% #problem with reading colnames
  filter(Région != "Brazil" & Région != "Canada" & Région != "Venezuela")


#NAs as empty character for better vizualization
Elasmo_with_OSPAR[is.na(Elasmo_with_OSPAR) == T] <- ""

#source : https://stackoverflow.com/questions/65914989/conditional-formatting-multiple-columns-in-reactable
#test
iucn_cols <- function(x){
  if(is.na(x) == T){""}
  else if(x == "CR"){"red"}
  else if(x == "EN") {"orange"}
  else if (x == "VU") {"gold"}
  else if (x == "NT") {"forestgreen"}
  else if (x == "LC") {"lightgreen" }
  else if(x == "DD") {"lightgrey"}
  else if(x == "declining") {"sandybrown"}
  else if(x == "stable"){"yellow"}
  else if(x == "recovering"){"aquamarine"}
  else if(x == "increasing"){"aquamarine"}
  else if(x == "unknown"){"lightgrey"}
  else if(x == "Good"){"lightgreen"}
  else if(x == "Poor"){"sandybrown"}
  else if(x == "Unknown"){"lightgrey"}
  else if(x == "3"){"lightblue"}
  else if(x == "NA"){"white"}
  else if(x == "Not applicable"){"white"}
  else if(x == "depleted"){"sandybrown"}
  else if (x == "decreasing"){"sandybrown"}
  else if(x == "very low"){"sandybrown"}
  else{""}}

stylefunc <- function(value, index, name) {
  color <- iucn_cols(value)
  list(background = color)
}

coldefs <- list(
  reactable::colDef(style = stylefunc)
)

cols <- Elasmo_with_OSPAR %>% select("Dernier statut", 10:33) %>% colnames()

#replicate list to required length
coldefs <- rep(coldefs,length(cols))

#name elements of list according to cols
names(coldefs) <- cols

#reactable package
Elasmo_IUCN_html <- reactable(Elasmo_with_OSPAR,
                  pagination = F, #all on one page
                  filterable = T,
                  showPageSizeOptions = T,
                  onClick = "select", #select the row when you click
                  highlight = T, #highlight the rows on hover
                  striped = T, #strip rows
                  columns = coldefs,
                  defaultColDef = colDef(minWidth = 120)
                )


save_reactable_test(Elasmo_IUCN_html, "html_output/Résultats_OE_statuts.html")
```

# Convention tables
```{r convention}
appendices_html <- reactable(Appendices, 
                             pagination = F, 
                             highlight = T, 
                             striped = T,
                             filterable = T)
save_reactable_test(appendices_html, "html_output/Appendices_html_table.html")
```

# OSPAR table
```{r ospar}
#create colors
status_color <- Status_OSPAR %>% 
  mutate(status_colors = dplyr::case_when(
  Last_status == 'Poor' ~ 'tomato',
  Last_status == 'Good' ~ 'forestgreen',
  Last_status == '?' ~ 'dodgerblue'
  ))


#reactable package
OSPAR_html <- reactable(status_color,
                        pagination = F,
                        highlight = T,
                        filterable = T,
                        striped = T,
                        defaultSorted = 'Last_status',
                        columns = list(
                          Last_status = colDef(
                            style = color_scales(status_color, color_ref = 'status_colors')),
                            status_colors = colDef(show = FALSE)
                          ))
save_reactable_test(OSPAR_html, "html_output/OSPAR_html_table.html")
```

# ICES advice
```{r ICES}
#bind stock_cats and stock_advice
ICES_advice <- left_join(ICES_advice, ICES_stock_cat, by = "Stock")

#pivot to wide format
ICES_wide <- ICES_advice %>% filter(Year %in% "2018":"2023") %>% pivot_wider(names_from = Year, values_from = Advice) %>% relocate(Stock, stock_category)

#reactable package
ICES_html <- reactable(ICES_wide,
                        pagination = F,
                        highlight = T,
                        striped = T,
                       filterable = T)

save_reactable_test(ICES_html, "html_output/ICES_html_table.html")
```
